export const BaseUrl = 'https://api.themoviedb.org/3/'
export const Access_Token = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNjAyNzZjYzg4ZDQ0MGU2OGI0ZWE0ZDg0OTM0MmVhMiIsInN1YiI6IjY2MmI4NjBkNWMwNzFiMDExZjVlYWEyOCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.otl2B8AXSIpMcQo45GcgJj5UQSslcHGTFpK2ZmJMp6c'
export const Image_BaseUrl ='https://image.tmdb.org/t/p/original/'
export const Action = 'https://api.themoviedb.org/3/discover/movie?with_genres=28'
export const Science_Fiction ='https://api.themoviedb.org/3/discover/movie?with_genres=878'